name: build and publish

on:
    push:
        branches:
            - master
        tags:
            - 'v*'

env:
    SOLUTION_NAME: 'BarLauncher-WebApp.sln' # set this to your application's name
    VERSION: '${{ github.ref_name }}'

jobs:
    build:
        name: Build and deploy
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Get the version (for tags)
              if: "contains(github.ref, 'refs/tags')"
              shell: bash
              run: echo "VERSION_LABEL=${GITHUB_REF#refs/tags/v}" >> "${GITHUB_ENV}"

            - name: Get the version (for branches)
              if: "!contains(github.ref, 'refs/tags')"
              shell: bash
              run: echo "VERSION_LABEL=${GITHUB_REF#refs/heads/}-latest" >> "${GITHUB_ENV}"

            - name: build ${{ env.SOLUTION_NAME }} (Version ${{ env.VERSION_LABEL }})
              run: |
                dotnet.exe build ${{ env.SOLUTION_NAME }} -c Release

                cd "BarLauncher.WebApp.Wox/bin/Release/net48"
                7z a -tzip "../../../../BarLauncher.WebApp.Wox-${{ env.VERSION_LABEL }}.wox" "*"
                cd "../../../.."

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: "BarLauncher.WebApp.Wox-${{ env.VERSION_LABEL }}"
                path: "BarLauncher.WebApp.Wox-${{ env.VERSION_LABEL }}.wox"


            - name: "Create release"
              if: "success() && contains(github.ref, 'refs/tags')"
              uses: "softprops/action-gh-release@v1"
              with:
                  body:
                  files: |
                    BarLauncher.WebApp.Wox-${{ env.VERSION_LABEL }}.wox
                  draft: false
                  prerelease: false
